version: "3"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  express1:
    build:
      context: ./server
    container_name: express1
    expose:
      - "3000"
    volumes:
      - ./src/express1:/src
      - /src/node_modules
    restart: "unless-stopped"
