openapi: 3.0.0
info:
  version: 1.0.0
  title: Scookie API docs
  description: Scookie 프로젝트의 API 문서입니다
  license:
    name: MIT
servers:
  - description: dev server
    url: 'http://127.0.0.1:3000'
paths:
  /points:
    get:
      summary: Get all points
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Points'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '600':
          $ref: '#/components/responses/DBError'
        default:
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Users:
      type: object
      required:
        - _id
        - email
        - nickname
        - password
      properties:
        _id:
          type: string
          description: ObjectID
        nickname:
          type: string
        password:
          type: string
        email:
          type: string
    Points:
      type: object
      required:
        - _id
        - userId
        - latitude
        - longitude
        - createdAt
        - updatedAt
      properties:
        _id:
          type: string
          description: ObjectID
        userId:
          type: string
          description: 유저 아이디
        latitude:
          type: string
          description: 위도
        longitude:
          type: string
          description: 경도
        createdAt:
          type: string
          description: 생성 시간
        updatedAt:
          type: string
          description: 수정 시간
        marker:
          type: object
          properties:
            address:
              type: string
              description: 주소
            placeName:
              type: string
              description: 장소 이름
            elapsedTime:
              type: number
              description: 경과 시간
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 내부 오류
    DBError:
      description: 데이터베이스 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 데이터베이스 에러
