openapi: 3.0.0
info:
  version: 1.0.0
  title: Scookie API docs
  description: Scookie 프로젝트의 API 문서입니다
  license:
    name: MIT
host: 'http://localhost:3000'
basePath: /
paths: !<tag:yaml.org,2002:js/undefined> ''
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - id
        - email
        - name
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        email:
          type: string
        name:
          type: string
        googleId:
          type: string
        profileImageUrl:
          type: string
        createdAt:
          type: datetime
        updatedAt:
          type: datetime
        deletedAt:
          type: datetime
    Workspace:
      type: object
      required:
        - id
        - name
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        name:
          type: string
        imageUrl:
          type: string
        createdAt:
          type: datetime
        updatedAt:
          type: datetime
        deletedAt:
          type: datetime
    UserWorkspace:
      type: object
      required:
        - createdAt
        - updatedAt
      properties:
        userId:
          type: integer
        workspaceId:
          type: integer
        createdAt:
          type: datetime
        updatedAt:
          type: datetime
    Channel:
      type: object
      required:
        - name
        - type
        - createdAt
        - updatedAt
      properties:
        name:
          type: string
        type:
          type: string
        createdAt:
          type: datetime
        updatedAt:
          type: datetime
        deletedAt:
          type: datetime
    Section:
      type: object
      required:
        - id
        - name
        - createdAt
        - updatedAt
      properties:
        id:
          type: number
        name:
          type: string
        userId:
          type: number
        workspaceId:
          type: number
        createdAt:
          type: datetime
        updatedAt:
          type: datetime
        deletedAt:
          type: datetime
    userChannelSection:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
      properties:
        id:
          type: number
        userId:
          type: number
        channelId:
          type: number
        sectionId:
          type: number
        createdAt:
          type: datetime
        updatedAt:
          type: datetime
        deletedAt:
          type: datetime
    Thread:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        userId:
          type: integer
        channelId:
          type: integer
        createdAt:
          type: datetime
        updatedAt:
          type: datetime
        deletedAt:
          type: datetime
    Message:
      type: object
      required:
        - id
        - content
        - isHead
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        content:
          type: string
        isHead:
          type: string
        userId:
          type: integer
        threadId:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
    Reaction:
      type: object
      required:
        - id
        - content
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        content:
          type: string
        messageId:
          type: integer
        userId:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
    File:
      type: object
      required:
        - id
        - url
        - type
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        url:
          type: string
        type:
          type: string
        messageId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 내부 오류
    DBError:
      description: 데이터베이스 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 데이터베이스 에러
